---
# Following the sample role CI
# https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml

sudo: required
dist: trusty

# https://docs.travis-ci.com/user/environment-variables/
#
# We don't have a full featured matrix support in travis:
# https://github.com/travis-ci/travis-ci/issues/1519
env:
  global:
    role_under_test: switch
    switch_user: admin
    ansible_ops: -vvv
    # Ubuntu/14.04 is the default ansible control machine distribution
    distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_ops: ""
  matrix:
    # Basic sanity check on both on Ubuntu14.04 and CentOS7 machines.
    - test_filename: test_version.yml
    - test_filename: test_version.yml
      distribution: centos
      version: 7
      init: /usr/lib/systemd/systemd
      run_ops: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  # OpenSwitch container
  - 'sudo docker build --pull=true --rm=true --file=roles/switch/tests/Dockerfile.openswitch --tag=ops:local roles/switch/tests'

  # Ansible control machine container
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:local tests'

script:
  - switch_id=$(mktemp)
  - ansible_id=$(mktemp)

  # Run OpenSwitch container in privileged and detached state
  - 'sudo docker run --privileged --detach -P -v /tmp:/tmp -v /dev/log:/dev/log -v /sys/fs/cgroup:/sys/fs/cgroup ops:local /sbin/init > "${switch_id}"'

  # Run Ansible control machine container in detached state
  - 'sudo docker run --detach --link "$(cat ${switch_id})":ops --volume="${PWD}"/roles:/etc/ansible/roles:rw --volume="${PWD}"/tests:/etc/ansible/tests:rw ${run_ops} ${distribution}-${version}:local ${init} > "${ansible_id}"'

  # Ansible syntax check
  - 'sudo docker exec --tty "$(cat ${ansible_id})" env TERM=xterm ansible-playbook /etc/ansible/tests/"${test_filename}" --syntax-check'

  # Run the test
  - 'sudo docker exec --tty "$(cat ${ansible_id})" env TERM=xterm ansible-playbook "${ansible_ops}" -u "${switch_user}" /etc/ansible/tests/"${test_filename}"'

  # Clenaup
  - 'sudo docker stop "$(cat ${ansible_id})"'
  - 'sudo docker stop "$(cat ${switch_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
